FROM python:3.9.18-slim

# Set the working directory
WORKDIR /mlflow

# Install MLflow
RUN pip install mlflow boto3

# Expose the port the app runs on
EXPOSE 5000

# Command to run the MLflow server
# CMD mlflow ui --backend-store-uri $BACKEND_URI --host 0.0.0.0

CMD mlflow server \
    --backend-store-uri sqlite:///mlflow.db \
    --default-artifact-root s3://mlops-s3-bucket-daniel/ \
    --host 0.0.0.0
